{% set version = "0.14.1" %}

package:
  name: cachecontrol-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/CacheControl/cachecontrol-{{ version }}.tar.gz
  sha256: 06ef916a1e4eb7dba9948cdfc9c76e749db2e02104a9a1277e8b642591a0f717

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8

outputs:
  - name: cachecontrol
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - doesitcache = cachecontrol._cmd:main
    requirements:
      host:
        - python >=3.8
        - flit-core >=3.2,<4
        - pip
      run:
        - python >=3.8
        - requests >=2.16.0
        - msgpack-python >=0.5.2,<2.0.0
    test: &test
      requires:
        - pip
      imports:
        - cachecontrol
      commands:
        - pip check
        - doesitcache --help

  - name: cachecontrol-with-redis
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("cachecontrol", exact=True) }}
        - python >=3.8
        - redis-py >=2.10.5
    test: *test

  - name: cachecontrol-with-filecache
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("cachecontrol", exact=True) }}
        - filelock >=3.8.0
        - python >=3.8
    test: *test

about:
  home: https://github.com/ionrock/cachecontrol
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: The httplib2 caching algorithms packaged up for use with requests
  description: |
    CacheControl is a port of the caching algorithms in httplib2 for use with
    requests session object.
    It was written because httplib2's better support for caching is often
    mitigated by its lack of threadsafety. The same is true of requests
    in terms of caching.
  doc_url: http://cachecontrol.readthedocs.io/
  dev_url: https://github.com/ionrock/cachecontrol

extra:
  feedstock-name: cachecontrol
  recipe-maintainers:
    - djsutherland
    - ocefpaf
