travis:
  secure:
    BINSTAR_TOKEN: ox3RdCz4ZamXU11oHqlvUyw2i4GB2z1e4lrkukpp50SNvQWf4vcCn4y5fN1UISAcSOk+i0eLF4Q0Brr3QWxaSV9xyUtw3+e8Ph2zMbB4N99PtiS86A9nVah+PVksyBYns7KCrHzGgSqrNDw///GyzHvHCljx15D5zg6WLZMxc7E7dY7prR0v8fBHR93M2j6ihd2GRvF53jcS1TmSGiOi99UTkbNQw6z/mfaOAwINAcKI7mbyOsQKJaS8VqAZ3lH5fJvwfw8RY4fi/QPjmXjZEdftrTK/SVyUdCDVC7+pxH3Rn9WfWW4YBCi+G/0/Ygwpdpoi8/gdOKTOUTvGD280pE2uSUWScsXQYTJuNFgcxu+GoxsD/Oq/OEqiRFpB2mo79KXD3YU2+p0LC/nQBfjmuM3+BJP6qAmR25Qc51LdNRI/3UHorqPDC65LVTGa+zCkkGr50rxR6ULQah8ELlOHqnwjQi/mkxAqAB/Oo0IUzCu1gQAAkJ59SPUYpc2yYAqzmZTxUvfQRRlmRpuoPIQOsbRp3TSAN1Xf8EWXbG/CJhm9HFjlbNhjnxD5EfNS/54B6q1GDkn/OFg11Hk+jUlGc0ATFSzdpxIGB4JG8FFlq5JRPfTODxG3R6jXlQFbI4aPUbY1ChLMA+whA+to/dpUooUhi2JSt+cvK8z+1x/e2sA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
